### ISSUE TITLE
What does expand_early do?

### ISSUE THREAD

**Issue by Qiyamah** [hverr/TinyCassette.jl#1]
Hi,
I was inspecting the code and didn't understand the following piece?

```Julia
@eval function overdub_recurse(inbounds, ctx, f, args...)
    # manual construction of the generated function in order to control the expand_early arg
    $(begin
          stub = Expr(:new,
                      Core.GeneratedFunctionStub,
                      :overdub_recurse_gen,
                      Any[:overdub_recurse, :inbounds, :ctx, :f, :args],
                      Any[],
                      @__LINE__,
                      QuoteNode(Symbol(@__FILE__)),
                      true)
          Expr(:meta, :generated, stub)
      end)
end
```

**Comment by hverr** [comment]
This hack actually came to me via @maleadt. As far as I understand and remember, at the time of writing this code (and maybe still) the Julia compiler did not always automatically expand generated functions during a compile cycle. Instead it would postpone its expansion until the generated function was called.

For our purposes we needed the compiler to always expand this generated function (because we were compiling for GPU). Inside the compiler each generated function has an _early expand_ flag, but there is no clean way to set it. So this piece of code manually creates a generated function AST node with the early expand flag set.

**Comment by maleadt** [comment]
What @hverr said. See https://github.com/JuliaLang/julia/pull/24852 for more details.
